skip_checks:
  - id: CKV_AWS_2
    comment: HTTP-only ALB for demo; TLS termination is a future update.
  - id: CKV_AWS_35
    comment: CloudTrail KMS encryption skipped for demo.
  - id: CKV_AWS_136
    comment: ECR KMS encryption skipped for demo.
  - id: CKV_AWS_150
    comment: Deletion protection disabled to allow clean teardown.
  - id: CKV_AWS_158
    comment: CloudWatch Logs KMS encryption skipped for demo.
  - id: CKV_AWS_338
    comment: Log retention set to 90 days for demo.