skip-check:
  - CKV_AWS_2   # HTTP-only ALB for demo; TLS termination is a future update.
  - CKV_AWS_35  # CloudTrail KMS encryption skipped for demo.
  - CKV_AWS_136 # ECR KMS encryption skipped for demo.
  - CKV_AWS_150 # Deletion protection disabled to allow clean teardown.
  - CKV_AWS_158 # CloudWatch Logs KMS encryption skipped for demo.
  - CKV_AWS_338 # Log retention set to 90 days for demo.
