skip-check:
  - CKV_AWS_2   # HTTP-only ALB for demo; TLS termination is a future update.
  - CKV_AWS_35  # CloudTrail KMS encryption skipped for demo.
  - CKV_AWS_136 # ECR KMS encryption skipped for demo.
  - CKV_AWS_150 # Deletion protection disabled to allow clean teardown.
  - CKV_AWS_158 # CloudWatch Logs KMS encryption skipped for demo.
  - CKV_AWS_338 # Log retention set to 90 days for demo.
  - CKV_AWS_18  # Logs bucket access logging skipped for demo.
  - CKV_AWS_26  # SNS KMS encryption skipped for demo.
  - CKV_AWS_130 # Public subnets assign public IPs by design.
  - CKV_AWS_144 # Cross-region replication skipped for demo.
  - CKV_AWS_145 # S3 KMS encryption skipped for demo.
  - CKV_AWS_260 # Public ALB ingress on port 80 is intentional for demo.
  - CKV_AWS_378 # HTTP target group is intentional for demo.
  - CKV_AWS_382 # SG egress is open for demo simplicity.
  - CKV_AWS_103 # TLS 1.2 not applicable to HTTP listeners.
  - CKV2_AWS_20 # HTTP to HTTPS redirect not enabled for demo.
  - CKV2_AWS_28 # WAF not enabled for demo.
  - CKV2_AWS_19 # NAT EIP not attached to EC2 instance by design.
  - CKV2_AWS_62 # S3 event notifications skipped for demo.
  - CKV2_AWS_5  # SG attachment check is a false positive in modules.
  - CKV2_AWS_10 # CloudTrail -> CloudWatch Logs integration skipped for demo.
  - CKV2_AWS_11 # VPC flow logs false positive across modules.
  - CKV2_AWS_65 # BucketOwnerPreferred retained for ALB log delivery.
